"""
This file is for running standalone tests or demonstrations of the data processing
pipeline, separate from the Streamlit application.
"""
import pandas as pd
import sys
import os

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))
from data_processor import DataProcessor

def run_data_processing_demo(file_path="temp_sample.csv"):
    """
    Creates an instance of DataProcessor and runs the data loading and cleaning
    steps using a provided file path for demonstration/testing.
    """
    try:
        # Create an instance of DataProcessor
        processor = DataProcessor()

        # Load your CSV file
        df = processor.load_data(file_path)

        # Clean the data
        clean_df = processor.clean_data(df)

        # Compute features
        features_df = processor.compute_basic_features(clean_df)

        print("\n--- Processed DataFrame Head ---")
        print(features_df.head().to_markdown())

        print("\n--- Summary Statistics ---")
        for k, v in processor.get_summary_stats(features_df).items():
            print(f"{k}: {v}")
            
        print("\nData processing demo successful.")

    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
        print("Please ensure you have run the data generation step in app.py or placed a CSV file at the specified path.")
    except Exception as e:
        print(f"An unexpected error occurred during data processing: {e}")

if __name__ == "__main__":
    # A dummy file path for demonstration/testing. 
    # This file must be generated by the Streamlit app's 'Generate Sample Data' button.
    print("--- Running Data Processing Demo (Requires 'temp_sample.csv') ---")
    run_data_processing_demo()
